# Generated by Django 4.0.1 on 2022-03-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_line',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
