# Generated by Django 4.0.1 on 2022-04-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userinfo_status_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size_line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
