# Generated by Django 4.0.1 on 2022-04-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
