# Generated by Django 4.0.1 on 2022-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_image_product_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
