# Generated by Django 4.0.1 on 2022-04-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orderinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
