# Generated by Django 4.0.1 on 2022-04-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_user_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_products',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='products_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='sale',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='size_line_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price_after_sale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userinfo'),
        ),
    ]
