# Generated by Django 4.0.1 on 2022-04-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cart_final_price_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_product_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_color', to='main.colors'),
            preserve_default=False,
        ),
    ]
