# Generated by Django 4.0.1 on 2022-03-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_collection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
    ]
