# Generated by Django 4.0.1 on 2022-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cartitem_cart_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_product_color',
            new_name='cart_item_color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='final_price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
