# Generated by Django 4.0.1 on 2022-03-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_collection_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='trend',
            new_name='new',
        ),
    ]
