# Generated by Django 4.0.1 on 2022-04-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_cart_product_color_cartitem_cart_item_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
