# Generated by Django 4.0.1 on 2022-04-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
