# Generated by Django 4.0.1 on 2022-04-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_image_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products_quantity',
            new_name='products_qty',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='size_line_number',
            new_name='size_line_qty',
        ),
    ]
