# Generated by Django 4.0.1 on 2022-04-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_products_quantity_cart_products_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='sale',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='total_price_after_sale',
            new_name='price',
        ),
    ]
