# Generated by Django 4.0.1 on 2022-03-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image3',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='others.aboutus')),
            ],
        ),
    ]
