# Generated by Django 4.0.1 on 2022-03-24 11:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_remove_aboutus_image1_remove_aboutus_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
