# Generated by Django 4.0.1 on 2022-04-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_alter_help_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='image',
        ),
        migrations.AlterField(
            model_name='imagehelp',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
