# Generated by Django 4.0.1 on 2022-04-01 09:18

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_remove_help_image_alter_imagehelp_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excellence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])])),
                ('header', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
