# Generated by Django 4.0.1 on 2022-04-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_slider_imageslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImageSlider',
        ),
    ]
