# Generated by Django 4.0.1 on 2022-04-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_slider_image_delete_imageslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_image', models.ImageField(upload_to='images')),
                ('header_image', models.ImageField(upload_to='images')),
                ('info', models.CharField(max_length=1000)),
                ('phone_header', models.CharField(max_length=20)),
                ('phone_footer', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('Phone_header', 'Phone_header'), ('Phone_footer', 'Phone_footer'), ('Email', 'Email'), ('Telegram', 'Telegram'), ('WhatsApp', 'Whatsapp')], max_length=100)),
            ],
        ),
    ]
