# Generated by Django 4.0.1 on 2022-04-05 10:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0010_footerheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerheader',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
