# Generated by Django 4.0.1 on 2022-04-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0011_alter_footerheader_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerheader',
            name='email',
        ),
        migrations.RemoveField(
            model_name='footerheader',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='footerheader',
            name='phone_footer',
        ),
        migrations.RemoveField(
            model_name='footerheader',
            name='phone_header',
        ),
        migrations.RemoveField(
            model_name='footerheader',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='footerheader',
            name='whatsapp',
        ),
    ]
