# Generated by Django 4.0.1 on 2022-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0012_remove_footerheader_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerheader',
            old_name='footer_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='footerheader',
            old_name='info',
            new_name='textfooter',
        ),
        migrations.RemoveField(
            model_name='footerheader',
            name='header_image',
        ),
        migrations.AddField(
            model_name='footerheader',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footerheader',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='type',
            field=models.CharField(choices=[('Number', 'Number'), ('Email', 'Email'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('WhatsApp', 'Whatsapp')], max_length=100),
        ),
    ]
