# Generated by Django 4.0.1 on 2022-04-05 11:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0014_header_delete_footerheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Number', 'Number'), ('Email', 'Email'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('WhatsApp', 'Whatsapp')], max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='header',
            name='link',
        ),
        migrations.RemoveField(
            model_name='header',
            name='type',
        ),
        migrations.AddField(
            model_name='header',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='textfooter',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
