# Generated by Django 4.0.1 on 2022-04-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0015_footer_remove_header_link_remove_header_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='textfooter',
            new_name='infotext',
        ),
    ]
