# Generated by Django 4.0.1 on 2022-04-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0016_rename_textfooter_header_infotext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='type',
            field=models.CharField(choices=[('Number', 'Number'), ('Email', 'Email'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Whatsapp', 'Whatsapp')], max_length=100),
        ),
    ]
